org_name = "ORG Name"
date = 2025-10-17
page_order = ["title", "blank"]

[style_config]
bg_color = "#dce0e8"
title_color = "#209fb5"
text_color = "#4c4f69"
critical_color = "#d20f39"
high_color = "#e64553"
medium_color = "#df8e1d"
low_color = "#40a02b"
info_color = "#04a5e5"

# Print
[pages.title.special]
special_page_type = "title"

[pages.title.blank]
special_page_type = "blank"
